name: Build
on:
  push:
    tags:
    - 'v*' # push events to main tagged with release version 
    branches:
      - "master"
      - "main"
jobs:
  create-release:
    name: Create release
    runs-on: [ubuntu-latest]
    outputs:
      release_url: ${{ steps.create_release_step.outputs.upload_url }}
    steps:
    - name: Get version
      id: get-version
      run: echo VER=$(cat version) >> "$GITHUB_OUTPUT"
    - name: Create Release
      id: create_release_step
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: latest
        release_name: Release ${{ steps.get-version.outputs.VER }}
        draft: false
        prerelease: false
    
  pyinstaller-build:
    name: Pyinstaller build
    needs: create-release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Create Executable
        uses: Martin005/pyinstaller-action@v1.2.0
        id: create-executable
        with:
          python_ver: '3.10'
          spec: 'ch9121.spec'
          requirements: 'requirements.txt'
          options: --onefile, --windowed,

      - name: Upload artifacts
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ needs.create-release.outputs.release_url }}
          asset_path: ${{ steps.create-executable.outputs.executable_path }}
          asset_name: ch9121_${{ runner.os }}
        
          
