name: Deploy
on:
  push:
    tags:
    - 'v*' # push events to main tagged with release version 

jobs:
  create-release:
    name: Create release
    runs-on: [ubuntu-latest]
    outputs:
      release_url: ${{ steps.create_release_step.outputs.upload_url }}
    steps:
    - name: Create Release
      id: create_release_step
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }} 
        draft: false
        prerelease: false
    
  pyinstaller-build-linux:
    name: Pyinstaller build on Ubuntu
    needs: create-release
    runs-on: [ubuntu-latest]
    steps:
      - name: Create Executable
        uses: Martin005/pyinstaller-action@v1.2.0
        id: create-executable
        with:
          python_ver: '3.10'
          spec: 'ch9121.spec'
          requirements: 'requirements.txt'

      - name: Upload artifacts
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ needs.create-release.outputs.release_url }}
          asset_path: ${{ steps.create-executable.outputs.executable_path }}/ch9121
          asset_name: ch9121_${{ runner.os }}
          asset_content_type: application/zip
          
  pyinstaller-build-windows:
    name: Pyinstaller build on Windows
    needs: create-release
    runs-on: [windows-latest]
    steps:
      - name: Create Executable
        uses: Martin005/pyinstaller-action@v1.2.0
        id: create-executable
        with:
          python_ver: '3.10'
          spec: 'ch9121.spec'
          requirements: 'requirements.txt'

      - name: Upload artifacts
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ needs.create-release.outputs.release_url }}
          asset_path: ${{ steps.create-executable.outputs.executable_path }}/ch9121.exe
          asset_name: ch9121_${{ runner.os }}
          asset_content_type: application/zip